# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83f5f9c6ab0d0fc43e2de36707013bc1a91b763818d7e4be65930cafd007f59b2686099113c9cef523d9820be75fbec89511b5ec736fa78cd80274e5355882a

test:
  secret_key_base: 53742dd181b6fa67c4484d5797763a2a19ccd5dfda72212b49165a79ab8a59e53fdde7cb7bf3d4bb601e6de005c4591d85da62c3cec7b46efb476f59af7bc24c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
